spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=UTC
    username: root
    password: 1234

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java


mybatis:
  mapper-locations: /static/mapping/*Mapper.xml
  type-aliases-package: com.example.graduationprojectspringboot.pojo
logging:
  level:
    com:
      example:
        graduationprojectspringboot:
          mapper: debug
